name: Local VM Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Your VM runner label
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run deployment commands
        run: |
          echo "Running inside the VM..."
          cd /home/admin/_work/simpleapp2\
          
          #git pull origin main
          # Add your app build/restart steps here, e.g.:
          # npm install
          # npm run build
          # systemctl restart myapp

          git checkout master
          git pull
          
          # Add your other deployment commands below
          # Example:
          # npm install
          # npm run build
          # systemctl restart myapp
