name:  trigger Name
# Trigger this workflow on pushes to the specified branch
on:
  push:
    branches:
      - main # Replace with your branch name
jobs:
  deploy:
    #runs-on: [self-hosted, Linux, X64] # Run this job on the latest Ubuntu version
    runs-on: 
      group: ubuntu-runners

    steps:
      - name: Checkout
        uses: actions/checkout@v2 # Check out your repository code

            
      - name: Deploy app
        run: |
          echo "Running deployment inside VM..."
          cd /home/test/
          git checkout master
          git pull
          # Add your other deployment commands below
          # Example:
          # npm install
          # npm run build
          # systemctl restart myapp
          
    permissions:
      contents: read
      actions: write
      id-token: write
